### ISSUE TITLE
error when saving steps

### ISSUE THREAD

**Issue by mohammadreza76** [puraminy/parsT5#2]
i was training parst5 on persian wikipedia and i got below error.

> [15:27:28] - DEBUG - absl -   Finished XLA compilation of broadcast_in_dim in 0.0159761905670166 sec
[15:27:28] - INFO - __main__ -   ######## Restoring check point ######
[15:27:28] - INFO - __main__ -   Restoring checkpoint from /content/drive/My Drive/T5
Traceback (most recent call last):
  File "/content/drive/My Drive/T5/run_t5_mlm_flax.py", line 817, in <module>
    state, resume_step = restore_checkpoint(training_args.resume_from_checkpoint, state)
  File "/content/drive/My Drive/T5/run_t5_mlm_flax.py", line 440, in restore_checkpoint
    opt_state = from_bytes(state.opt_state, f.read())
  File "/usr/local/lib/python3.7/dist-packages/flax/serialization.py", line 369, in from_bytes
    return from_state_dict(target, state_dict)
  File "/usr/local/lib/python3.7/dist-packages/flax/serialization.py", line 65, in from_state_dict
    return ty_from_state_dict(target, state)
  File "/usr/local/lib/python3.7/dist-packages/flax/serialization.py", line 156, in <lambda>
    lambda xs, state_dict: tuple(_restore_list(list(xs), state_dict)))
  File "/usr/local/lib/python3.7/dist-packages/flax/serialization.py", line 114, in _restore_list
    y = from_state_dict(xs[i], state_dict[str(i)])
  File "/usr/local/lib/python3.7/dist-packages/flax/serialization.py", line 65, in from_state_dict
    return ty_from_state_dict(target, state)
  File "/usr/local/lib/python3.7/dist-packages/flax/serialization.py", line 146, in _restore_namedtuple
    raise ValueError('The field names of the state dict and the named tuple do not match,'
ValueError: The field names of the state dict and the named tuple do not match, got {'count', 'stats'} and {'count', 'v_col', 'v', 'v_row'}.

and above error was after trained part of data.

> [15:13:09] - WARNING - datasets.builder -   Using custom data configuration default-09f28664c3007f01
[15:13:09] - WARNING - datasets.builder -   Reusing dataset text (/content/drive/My Drive/cache/text/default-09f28664c3007f01/0.0.0/4b86d314f7236db91f0a0f5cda32d4375445e64c5eda2692655dd99c2dac68e8)
[15:13:09] - INFO - __main__ -   max_seq_length: 256
[15:13:09] - INFO - __main__ -   ###################### Before MAP ##############
100% 2483/2483 [08:13<00:00,  5.03ba/s]
100% 131/131 [00:26<00:00,  4.92ba/s]
[15:21:50] - INFO - __main__ -   ###################### After MAP ##############
[15:21:50] - INFO - __main__ -   ###################### Before MAP 2 ##############
100% 2483/2483 [05:19<00:00,  7.77ba/s]
100% 131/131 [00:17<00:00,  7.57ba/s]
[15:27:28] - INFO - __main__ -   ###################### After MAP 2 ##############
2022-04-10 15:27:28.236600: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
[15:27:28] - DEBUG - absl -   Finished tracing + transforming _threefry_split for jit in 0.003953456878662109 sec.

and the running  code is below.

> model_folder="/content/drive/My Drive/T5"
cache_folder="/content/drive/My Drive/cache"
data_path="/content/drive/My Drive/T5/Data/cleaned.txt"

!python "/content/drive/My Drive/T5/run_t5_mlm_flax.py" \
  --model_name_or_path="/content/drive/My Drive/T5" \
	--output_dir="/content/drive/My Drive/T5" \
	--cache_dir="/content/drive/My Drive/cache" \
  --model_type="t5" \
	--config_name="/content/drive/My Drive/T5" \
	--tokenizer_name="/content/drive/My Drive/T5" \
	--train_file="/content/drive/My Drive/T5/Data/cleaned.txt" \
	--max_seq_length="256" \
	--per_device_train_batch_size="32" \
	--per_device_eval_batch_size="32" \
	--adafactor \
	--max_eval_steps="12000" \
	--learning_rate="0.05" \
	--weight_decay="0.001" \
	--warmup_steps="2000" \
	--logging_steps="500" \
  --resume_from_checkpoint="/content/drive/My Drive/T5"

**Comment by puraminy** [comment]
As you read in README file, my code is based on the following code:

https://github.com/huggingface/transformers/blob/main/examples/flax/language-modeling/run_t5_mlm_flax.py

The error occurs when you want to `resume_from_checkpoint`. I currently don't know what it can't restore the saved state. However, as an alternative, you can remove this flag. 

You have also specified `model_name_or_path`. So, if it points to the parsT5 or parsT5-base models, then it can loads the pre-trained model weights, and there is no need to specify resume from last checkpoints. Then whenever you saved a checkpoint and wanted to resume from that point you can set that flag.

**Comment by mohammadreza76** [comment]
thanks, when we removed it ,that error fixed although after we got another error which to fixed it ,we had to add eval_step to instructions of running you write in github.

**Comment by puraminy** [comment]
what did you use for  `model_name_or_path`? was it `parsT5` or `parsT5-base`? 

Both can be downloaded from huggingface
